In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import fetch_california_housing

In [4]:
housing = fetch_california_housing(as_frame = True)

In [5]:
df = housing.frame

In [6]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

In [8]:
df.describe().round(2)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
count,20640.00,20640.00,20640.00,20640.00,20640.00,20640.00,20640.00,20640.00,20640.00
mean,3.87,28.64,5.43,1.10,1425.48,3.07,35.63,-119.57,2.07
std,1.90,12.59,2.47,0.47,1132.46,10.39,2.14,2.00,1.15
min,0.50,1.00,0.85,0.33,3.00,0.69,32.54,-124.35,0.15
25%,2.56,18.00,4.44,1.01,787.00,2.43,33.93,-121.80,1.20
50%,3.53,29.00,5.23,1.05,1166.00,2.82,34.26,-118.49,1.80
75%,4.74,37.00,6.05,1.10,1725.00,3.28,37.71,-118.01,2.65
max,15.00,52.00,141.91,34.07,35682.00,1243.33,41.95,-114.31,5.00

In [9]:
X = df.drop('MedHouseVal', axis=1)
y = df['MedHouseVal']

In [10]:
X.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [11]:
y.head()

0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: MedHouseVal, dtype: float64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_tmp, y_train, y_tmp = train_test_split(X, y, test_size=0.3, random_state=42)

In [14]:
X_val, X_test, y_val, y_test = train_test_split(X_tmp, y_tmp, test_size=0.5, random_state=42)

In [15]:
print(len(X_train))
print(len(X_val))
print(len(X_test))

14448
3096
3096

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler = StandardScaler()

In [18]:
X_train_scaled = scaler.fit_transform(X_train)

In [19]:
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

In [20]:
pd.Series(X_train_scaled.mean(axis=0), index=X.columns).round(5).to_dict()

{'MedInc': 0.0,
 'HouseAge': -0.0,
 'AveRooms': -0.0,
 'AveBedrms': -0.0,
 'Population': 0.0,
 'AveOccup': 0.0,
 'Latitude': -0.0,
 'Longitude': -0.0}

In [21]:
pd.Series(X_train_scaled.std(axis=0), index=X.columns).round(4).to_dict()

{'MedInc': 1.0,
 'HouseAge': 1.0,
 'AveRooms': 1.0,
 'AveBedrms': 1.0,
 'Population': 1.0,
 'AveOccup': 1.0,
 'Latitude': 1.0,
 'Longitude': 1.0}

In [22]:
pd.Series(X_val_scaled.mean(axis=0), index=X.columns).round(5).to_dict()

{'MedInc': -0.02146,
 'HouseAge': 0.01635,
 'AveRooms': -0.03335,
 'AveBedrms': -0.02801,
 'Population': 0.00125,
 'AveOccup': -0.01532,
 'Latitude': -0.05636,
 'Longitude': 0.05634}

In [23]:
pd.Series(X_val_scaled.std(axis=0), index=X.columns).round(4).to_dict()

{'MedInc': 0.9736,
 'HouseAge': 1.0052,
 'AveRooms': 0.7313,
 'AveBedrms': 0.6647,
 'Population': 1.0433,
 'AveOccup': 0.0666,
 'Latitude': 0.9986,
 'Longitude': 0.9945}

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
from sklearn.pipeline import Pipeline

In [26]:
lr = LinearRegression()

In [27]:
lr.fit(X_train_scaled, y_train)

LinearRegression()

In [28]:
y_pred_val = lr.predict(X_val_scaled)
y_pred_test = lr.predict(X_test_scaled)

In [29]:
pd.DataFrame({'Feature': X.columns, 'Coefficients': lr.coef_})

      Feature  Coefficients
0      MedInc      0.849222
1    HouseAge      0.122119
2    AveRooms     -0.299558
3   AveBedrms      0.348410
4  Population     -0.000884
5    AveOccup     -0.041698
6    Latitude     -0.893856
7   Longitude     -0.868617

In [30]:
y_val.values[:5]

array([1.225, 3.204, 4.507, 2.343, 1.019])

In [31]:
y_pred_val[:5]

array([1.37655112, 3.27141161, 3.94042122, 2.87266089, 1.98833994])

In [32]:
from sklearn.metrics import (
    mean_squared_error, 
    mean_absolute_error, 
    r2_score, 
    mean_absolute_error,
    mean_absolute_percentage_error
)

In [33]:
mean_squared_error(y_val, y_pred_val)

0.5408750691093342

In [34]:
mean_absolute_error(y_val, y_pred_val)

0.5334518974729614

In [35]:
r2_score(y_val, y_pred_val)

0.5848261822866255

In [36]:
mean_absolute_error(y_val, y_pred_val)

0.5334518974729614

In [37]:
mean_absolute_percentage_error(y_val, y_pred_val)

0.3215444663403093

In [38]:
from sklearn.model_selection import cross_validate, KFold

In [39]:
cv = KFold(n_splits=5, shuffle=True, random_state=42)

In [40]:
pipe_lr = Pipeline([
    ('scaler', StandardScaler()),
    ('reg', LinearRegression())
])

In [41]:
cv_result = cross_validate(
    pipe_lr,
    X_train,
    y_train,
    cv=cv,
    scoring=['neg_root_mean_squared_error', 'r2']
)

In [42]:
cv_result

{'fit_time': array([0.00246501, 0.00203896, 0.00221419, 0.00229597, 0.00198078]),
 'score_time': array([0.00071502, 0.00090694, 0.00094295, 0.00073814, 0.00080013]),
 'test_neg_root_mean_squared_error': array([-0.73145917, -0.74079427, -0.72898565, -0.71494259, -0.70695715]),
 'test_r2': array([0.61127907, 0.58190816, 0.58646706, 0.63255644, 0.62495045])}

In [43]:
cv_result['test_neg_root_mean_squared_error']

array([-0.73145917, -0.74079427, -0.72898565, -0.71494259, -0.70695715])

In [44]:
from sklearn.ensemble import RandomForestRegressor

In [45]:
pipe_rf = Pipeline([
    ('scaler', StandardScaler()),
    ('reg', RandomForestRegressor())
])

In [46]:
pipe_rf.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('reg', RandomForestRegressor())])

In [47]:
rf_model = pipe_rf.named_steps['reg']

In [48]:
importance_native = rf_model.feature_importances_

In [49]:
importance_native

array([0.52495309, 0.05338905, 0.04541989, 0.02956019, 0.03121584,
       0.13785308, 0.08841623, 0.08919264])

In [50]:
pd.Series(importance_native, index=X.columns)

MedInc        0.524953
HouseAge      0.053389
AveRooms      0.045420
AveBedrms     0.029560
Population    0.031216
AveOccup      0.137853
Latitude      0.088416
Longitude     0.089193
dtype: float64

In [51]:
from sklearn.inspection import permutation_importance

In [52]:
perm = permutation_importance(
    pipe_rf, X_val, y_val, n_repeats=10, random_state=42, scoring='r2'
)

In [53]:
pd.Series(perm.importances_mean, index=X.columns)

MedInc        0.735442
HouseAge      0.073440
AveRooms      0.025263
AveBedrms     0.008057
Population    0.006647
AveOccup      0.211206
Latitude      0.451583
Longitude     0.339677
dtype: float64

In [54]:
pd.Series(perm.importances_std, index=X.columns)

MedInc        0.014371
HouseAge      0.004938
AveRooms      0.001540
AveBedrms     0.001144
Population    0.001542
AveOccup      0.012331
Latitude      0.010859
Longitude     0.004728
dtype: float64

In [55]:
import shap

/Users/Larry.Jin/miniconda3/envs/prep/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [56]:
explainer = shap.TreeExplainer(rf_model)

In [57]:
# shap_values = explainer.shap_values(X_val)

In [58]:
from sklearn.model_selection import RandomizedSearchCV

In [62]:
from scipy.stats import randint
params = {
    'reg__n_estimators': randint(100, 500),
    'reg__max_depth': [None, 10, 15, 20],
    'reg__min_samples_split': randint(2, 20)
}

In [63]:
rs = RandomizedSearchCV(
    pipe_rf,
    params,
    n_iter=25,
    cv=KFold(n_splits=5, shuffle=True, random_state=42),
    scoring='neg_root_mean_squared_error',
    random_state=42,
    n_jobs=-1,
    refit=True
)

In [64]:
rs.fit(X_train, y_train)

/Users/Larry.Jin/miniconda3/envs/prep/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

RandomizedSearchCV(cv=KFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                             ('reg', RandomForestRegressor())]),
                   n_iter=25, n_jobs=-1,
                   param_distributions={'reg__max_depth': [None, 10, 15, 20],
                                        'reg__min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x12b700690>,
                                        'reg__n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x12b3a4d90>},
                   random_state=42, scoring='neg_root_mean_squared_error')

In [65]:
rs.best_params_

{'reg__max_depth': None, 'reg__min_samples_split': 3, 'reg__n_estimators': 439}

In [66]:
rs.best_score_

np.float64(-0.5178778389433422)

In [72]:
best = rs.best_estimator_
y_test_pred = best.predict(X_test)

In [73]:
mean_squared_error(y_test, y_test_pred)

0.2399368365992177

In [75]:
mean_absolute_error(y_test, y_test_pred)

0.3232548361329721

In [76]:
r2_score(y_test, y_test_pred)

0.8185472694242852

In [77]:
mean_absolute_percentage_error(y_test, y_test_pred)

0.18713867562227554